# Generated by Django 5.0.7 on 2024-10-18 06:34

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('test_series', 'Test Series'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.CharField(blank=True, max_length=255, null=True)),
                ('document_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
