# Generated by Django 5.0.7 on 2024-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeresource',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freeresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document')], max_length=20),
        ),
    ]
