# Generated by Django 5.0.7 on 2024-09-20 06:29

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/', verbose_name='Thumbnail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount')),
                ('effective_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Effective Price')),
                ('validity_type', models.CharField(choices=[('single', 'Single Validity'), ('multiple', 'Multiple Validity'), ('lifetime', 'Lifetime Validity'), ('expiry_date', 'Expiry Date')], default='single', max_length=20, verbose_name='Validity Type')),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration Value')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=10, verbose_name='Duration Unit')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedCourseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('internet_handling_charges', models.BooleanField(default=False, verbose_name='Internet Handling Charges')),
                ('tax_details', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (18, '18%'), (25, '25%')], default=0, verbose_name='Tax Details')),
                ('course_sharing', models.BooleanField(default=False, verbose_name='Course Sharing')),
                ('offline_material', models.BooleanField(default=False, verbose_name='Course Has Offline Material For Shipment')),
                ('offline_download_videos', models.BooleanField(default=False, verbose_name='Offline Download Of Videos')),
                ('pdf_download_app', models.BooleanField(default=False, verbose_name='PDF Download Permissions in APP')),
                ('pdf_access_web', models.BooleanField(default=False, verbose_name='PDF permissions on Web')),
                ('live_classes', models.BooleanField(default=False, verbose_name='LIVE Classes')),
                ('add_restrictions_videos', models.BooleanField(default=False, verbose_name='Add Restrictions To Videos')),
                ('update_existing_videos', models.BooleanField(default=False, verbose_name='Update Existing Videos')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_settings', to='course.course')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='course.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
