# Generated by Django 5.0.7 on 2024-09-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_effective_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='created_by',
        ),
    ]
