# Generated by Django 5.0.7 on 2024-11-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursefaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseValidityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_value', models.PositiveIntegerField(verbose_name='Duration Value')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=10, verbose_name='Duration Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount')),
                ('effective_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Effective Price')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_periods', to='course.course')),
            ],
            options={
                'verbose_name': 'Course Validity',
                'verbose_name_plural': 'Course Validity Periods',
            },
        ),
    ]
