# Generated by Django 5.0.7 on 2024-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_instructor_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(max_length=255, verbose_name='Thumbnail'),
        ),
    ]
