# Generated by Django 5.0.7 on 2024-09-22 18:34

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Folder Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Folder Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='course.course')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.folder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
