# Generated by Django 5.0.7 on 2024-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursevalidityperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevalidityperiod',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
