# Generated by Django 5.0.7 on 2024-11-12 08:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursevalidityperiod_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchaseorder',
            name='course_joined_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 12, 8, 56, 36, 852441, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursepurchaseorder',
            name='course_validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursevalidityperiod'),
        ),
    ]
