# Generated by Django 5.0.7 on 2024-09-22 20:48

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_folder_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='description',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Lecture Title')),
                ('document', models.FileField(upload_to='videos/', verbose_name='Lecture Video')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.folder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
