# Generated by Django 5.0.7 on 2024-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_coursepurchaseorder_course_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchaseorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coursepurchaseorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursepurchaseorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepurchaseorder',
            name='course_joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
