# Generated by Django 5.0.7 on 2024-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursepurchaseorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
    ]
