# Generated by Django 5.0.7 on 2024-10-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursepurchaseorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepurchaseorder',
            options={'ordering': ['-created']},
        ),
    ]
