# Generated by Django 5.0.7 on 2024-11-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_delete_announcementseenstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',), 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
    ]
