# Generated by Django 5.0.7 on 2024-10-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesession',
            options={'ordering': ('-created_at',), 'verbose_name': 'Device Session', 'verbose_name_plural': 'Device Sessions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-created',)},
        ),
    ]
