# Generated by Django 5.0.7 on 2024-09-10 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_result',
            field=models.FileField(blank=True, upload_to='results/college/', verbose_name='College Result'),
        ),
        migrations.AlterField(
            model_name='student',
            name='correspondence_address',
            field=models.TextField(blank=True, verbose_name='Correspondence Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='correspondence_address_pincode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Correspondence Address Pincode'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_college',
            field=models.FloatField(blank=True, verbose_name='Marks in College (%)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_xii',
            field=models.FloatField(blank=True, verbose_name='Marks in XII (%)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Parent Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_profile_photo',
            field=models.ImageField(blank=True, upload_to='parent_photos/', verbose_name='Parent Profile Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address_pincode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Permanent Address Pincode'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='x_result',
            field=models.FileField(blank=True, upload_to='results/x/', verbose_name='X Result'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xii_result',
            field=models.FileField(blank=True, upload_to='results/xii/', verbose_name='XII Result'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Session',
                'verbose_name_plural': 'Device Sessions',
                'unique_together': {('user', 'device_type')},
            },
        ),
    ]
