# Generated by Django 5.0.7 on 2024-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_about_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks_college',
            field=models.FloatField(blank=True, null=True, verbose_name='Marks in College (%)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_xii',
            field=models.FloatField(blank=True, null=True, verbose_name='Marks in XII (%)'),
        ),
    ]
