# Generated by Django 5.0.7 on 2024-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='merit_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
