# Generated by Django 5.0.7 on 2024-11-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_module_modulepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'ordering': ('id',)},
        ),
    ]
