# Generated by Django 5.0.7 on 2024-10-11 11:52

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('enquiry_date', models.DateField(verbose_name='Enquiry Date')),
                ('source', models.CharField(choices=[('Justdial', 'Justdial'), ('Sulekha', 'Sulekha'), ('Hoardings', 'Hoardings'), ('Online Marketing', 'Online Marketing'), ('Reference', 'Reference'), ('Others', 'Others')], max_length=50, verbose_name='Source')),
                ('enquiry_status', models.CharField(choices=[('High Interest', 'High Interest'), ('Medium Interest', 'Medium Interest'), ('Low Interest', 'Low Interest'), ('Converted', 'Converted'), ('Lost', 'Lost')], max_length=50, verbose_name='Enquiry Status')),
                ('class_and_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Class and Subject')),
                ('followup_type', models.CharField(max_length=255, verbose_name='Followup Type')),
                ('followup_date', models.DateField(verbose_name='Followup Date')),
                ('followup_time', models.TimeField(verbose_name='Followup Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
