# Generated by Django 5.0.7 on 2024-10-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-created',), 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
