# Generated by Django 5.0.7 on 2024-09-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'get_latest_by': 'modified', 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
