# Generated by Django 5.0.7 on 2024-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batchpurchaseorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-created',), 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-created',), 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='batchpurchaseorder',
            options={'ordering': ('-created',), 'verbose_name': 'Batch Purchase Order', 'verbose_name_plural': 'Batch Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-created',), 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ('-created',), 'verbose_name': 'Live Class', 'verbose_name_plural': 'Live Classes'},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ('-created',), 'verbose_name': 'Study Material', 'verbose_name_plural': 'Study Material'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created',), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='batch',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail'),
        ),
    ]
