# Generated by Django 5.0.7 on 2024-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_enrollment_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='link',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='common_host_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live Class commonHostLink'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='common_moderator_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live Class commonModeratorLink'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='common_participant_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live Class commonParticipantLink'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='host_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live Class host_link'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Class Date'),
        ),
    ]
