# Generated by Django 5.0.7 on 2024-10-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_folder_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='analytics',
            field=models.JSONField(blank=True, null=True, verbose_name='Analytics'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='browser',
            field=models.JSONField(blank=True, max_length=255, null=True, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='live_class_link',
            field=models.URLField(blank=True, null=True, verbose_name='Live class Joining Link '),
        ),
        migrations.AddField(
            model_name='attendance',
            name='os',
            field=models.JSONField(blank=True, max_length=255, null=True, verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Total Time'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='class_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class ID'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recording Status'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='Recording URL'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
