# Generated by Django 5.0.7 on 2024-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_remove_liveclass_link_liveclass_common_host_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
    ]
