# Generated by Django 5.0.7 on 2024-10-10 11:06

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_batch_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('structure_name', models.CharField(max_length=255, verbose_name='Structure Name')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fee Amount')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Number of Installments')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.feestructure', verbose_name='Fee Structure'),
        ),
    ]
