# Generated by Django 5.0.7 on 2024-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_attendance_analytics_attendance_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Class Date'),
        ),
    ]
