# Generated by Django 5.0.7 on 2024-10-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_alter_liveclass_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='live_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='batch.liveclass'),
        ),
    ]
