# Generated by Django 5.0.7 on 2024-10-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_remove_attendance_total_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Time'),
        ),
    ]
