# Generated by Django 5.0.7 on 2024-10-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0009_attendance_total_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ('-date',), 'verbose_name': 'Live Class', 'verbose_name_plural': 'Live Classes'},
        ),
    ]
