# Generated by Django 5.0.7 on 2024-11-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0012_offlineclass_timeslot_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batch'),
        ),
    ]
