# Generated by Django 5.0.7 on 2024-11-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0013_offlineclass_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_classes', to='batch.batch'),
        ),
    ]
