# Generated by Django 5.0.7 on 2024-11-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0014_alter_offlineclass_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='manual_payment_approval',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Manual Approval'),
        ),
    ]
