# Generated by Django 5.0.7 on 2024-11-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0016_batchfaculty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
