# Generated by Django 5.0.7 on 2024-11-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0017_alter_attendance_unique_together'),
        ('payment', '0003_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpurchaseorder',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_purchase_orders', to='payment.transaction'),
        ),
    ]
