# Generated by Django 5.0.7 on 2024-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0018_alter_batchpurchaseorder_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
