# Generated by Django 5.0.7 on 2024-12-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0020_alter_file_options_alter_folder_options_file_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='param_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_chapters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_enrolled',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='param_videos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
