# Generated by Django 5.0.7 on 2024-10-17 06:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0002_remove_testseries_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
