# Generated by Django 5.0.7 on 2024-10-17 06:30

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('test_series', '0003_testseries_highlights_delete_highlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeriesPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_series_purchases', to=settings.AUTH_USER_MODEL)),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='test_series.testseries')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_series_purchase_orders', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'Test Series Purchase Order',
                'verbose_name_plural': 'Test Series Purchase Orders',
                'ordering': ('-created',),
            },
        ),
    ]
