# Generated by Django 5.0.7 on 2024-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0004_testseriespurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
    ]
