# Generated by Django 5.0.7 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0006_testseries_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
