# Generated by Django 5.0.7 on 2024-11-26 07:52

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0007_alter_testseries_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('delivery_status', models.CharField(choices=[('shipped', 'Shipped'), ('in-transit', 'In-Transit'), ('delivered', 'Delivered'), ('delivery-pending', 'Delivery Pending')], default='delivery-pending', max_length=20)),
                ('gst', models.PositiveSmallIntegerField(default=18)),
                ('test_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_product', to='test_series.testseries')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
