# Generated by Django 5.0.7 on 2024-11-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0009_testseries_gst_physicalproductorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
