# Generated by Django 5.0.7 on 2024-11-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0010_alter_testseries_is_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalproductorder',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_product_order', to='test_series.testseriespurchaseorder'),
        ),
    ]
