# Generated by Django 5.0.7 on 2024-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0011_physicalproductorder_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalproductorder',
            name='awb_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
