# Generated by Django 5.0.7 on 2024-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0012_physicalproductorder_awb_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalproductorder',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalproductorder',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalproductorder',
            name='delivery_status',
            field=models.CharField(choices=[('order-placed', 'Order Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('in-transit', 'In-Transit')], default='order-placed', max_length=20),
        ),
    ]
