# Generated by Django 5.0.7 on 2024-09-25 06:32

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0010_alter_file_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Offer Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('coupon_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Coupon Type')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Discount Amount')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date and Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time')),
                ('lifetime', models.BooleanField(default=False, verbose_name='Lifetime')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Order Value')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Uses')),
                ('usage_per_student', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Per Student')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visibility')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('total_applied', models.PositiveIntegerField(default=0, verbose_name='Total Applied')),
                ('courses', models.ManyToManyField(blank=True, related_name='coupons', to='course.course', verbose_name='Courses')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['code'], name='coupon_coup_code_e43490_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='coupon_coup_start_d_409d7b_idx'), models.Index(fields=['status'], name='coupon_coup_status_e375ec_idx')],
                'unique_together': {('code', 'coupon_type')},
            },
        ),
    ]
