# Generated by Django 5.0.7 on 2024-10-11 11:52

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Offer Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('coupon_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Coupon Type')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Discount Amount')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date and Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date and Time')),
                ('lifetime', models.BooleanField(default=False, verbose_name='Lifetime')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Order Value')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Uses')),
                ('usage_per_student', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Per Student')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visibility')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('total_applied', models.PositiveIntegerField(default=0, verbose_name='Total Applied')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created'],
            },
        ),
    ]
