# Generated by Django 5.0.7 on 2024-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='course.course', verbose_name='Courses'),
        ),
    ]
