# Generated by Django 5.0.7 on 2024-10-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='courses',
        ),
    ]
