# Generated by Django 5.0.7 on 2024-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_coupon_courses_coupon_is_all_courses_coupon_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Coupon Code'),
        ),
    ]
