# Generated by Django 5.0.7 on 2024-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
    ]
