# Generated by Django 5.0.7 on 2024-11-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
    ]
