# Generated by Django 5.0.7 on 2024-10-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_options_transaction_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
