# Generated by Django 5.0.7 on 2024-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
    ]
