# Generated by Django 5.0.7 on 2024-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_invoice_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_counter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
